// Kurssilinkit ja -tiedot. Jaettu etusivun ja tasotestin kesken.
// Hinnat, paikat ja sulkeutumispäivät ovat vielä vahvistamattomia esimerkkejä
// — päivitä omilla luvuillasi.
export const COURSES = [
  {
    code: "B",
    field: "Lääketiede & hammaslääketiede",
    koulutus: "Lääketiede, hammaslääketiede, eläinlääketiede, farmasia ja biolääketiede",
    title: "Lääkiksen valmennuskurssi 2027",
    href: "https://valintakoeb.fi",
    rating: 4.8,
    price: "149 €",
    oldPrice: "299 €",
    vipPrice: "499 €",
    vipOldPrice: "699 €",
    seatsLeft: 7,
    closing: "Ilmoittautuminen sulkeutuu 31.1.",
    popular: true,
    recommend:
      "Sinua vetää puoleensa ihmisten auttaminen ja luonnontieteet. Lääketieteen valintakoe (B) on Suomen kilpailluin — siksi järjestelmällinen valmistautuminen ratkaisee.",
    perks: [
      "Yli 1 200 koetehtävää ja 12 simuloitua koetta",
      "Live-klinikat keväällä ja tallenteet",
      "Teoria ja painetut kirjat tulossa keväällä",
    ],
  },
  {
    code: "E",
    field: "Kasvatusala & liikuntapedagogiikka",
    koulutus: "Luokanopettaja, varhaiskasvatus, erityisopettaja ja liikuntapedagogiikka",
    title: "Kasvatusalan valmennuskurssi 2027",
    href: "https://valintakoee.fi",
    rating: 4.6,
    price: "99 €",
    oldPrice: "199 €",
    vipPrice: "149 €",
    vipOldPrice: "249 €",
    seatsLeft: 12,
    closing: "Vain kevään ryhmä jäljellä",
    popular: false,
    recommend:
      "Haluat tukea ja kasvattaa ihmisiä. Kasvatusalan valintakoe (E) yhdistää soveltuvuuden ja aineiston — oikealla tekniikalla erotut hakijajoukosta.",
    perks: [
      "Soveltuvuus- ja aineistokokeen harjoitustehtävät",
      "Live-klinikat keväällä ja tallenteet",
      "Teoria ja painetut kirjat tulossa keväällä",
    ],
  },
  {
    code: "F",
    field: "Kauppatieteet",
    koulutus: "Kauppatieteet, taloustiede, tietojärjestelmätiede sekä ympäristö- ja elintarviketalous",
    title: "Kauppiksen valmennuskurssi 2027",
    href: "https://valintakoefpro.com",
    rating: 4.7,
    price: "99 €",
    oldPrice: "199 €",
    vipPrice: "149 €",
    vipOldPrice: "249 €",
    seatsLeft: 9,
    closing: "Early bird -hinta päättyy pian",
    popular: false,
    recommend:
      "Sinua kiinnostaa johtaminen, talous ja vaikuttaminen. Kauppatieteiden valintakoe (F) palkitsee ennakkomateriaalin hallinnan — ja siihen mentorimme on juuri päässyt sisään.",
    perks: [
      "Matematiikan ja taloustiedon harjoitustehtävät",
      "Mentorina alalle juuri tällä kurssilla päässyt opiskelija",
      "Live-klinikat keväällä ja tallenteet",
      "Teoria ja painetut kirjat tulossa keväällä",
    ],
  },
  {
    code: "A",
    field: "Tekniikka & luonnontieteet (DI)",
    koulutus: "Diplomi-insinööri, tietojenkäsittelytiede, fysiikka, kemia ja matemaattiset tieteet",
    title: "Tekniikan ja DI-valintakokeen valmennuskurssi 2027",
    href: "https://valintakoea.fi",
    rating: 4.9,
    price: "99 €",
    oldPrice: "199 €",
    vipPrice: "149 €",
    vipOldPrice: "249 €",
    seatsLeft: 15,
    closing: "Ryhmäkoko rajattu henkilökohtaisen ohjauksen vuoksi",
    popular: false,
    recommend:
      "Pidät logiikasta, matematiikasta ja asioiden rakentamisesta. Tekniikan valintakoe (A) mittaa ongelmanratkaisua — sitä voi treenata, ja sillä erotut.",
    perks: [
      "Matematiikan, fysiikan ja kemian harjoitustehtävät",
      "Live-klinikat keväällä ja tallenteet",
      "Teoria ja painetut kirjat tulossa keväällä",
    ],
  },
  {
    code: "C",
    field: "Biologia & ympäristötieteet",
    koulutus: "Biologia, ympäristötieteet, elintarviketieteet, geotieteet, maantiede ja metsätieteet",
    title: "Biologian ja luonnontieteiden valmennuskurssi 2027",
    href: "https://valintakoec.fi",
    rating: 4.5,
    price: "99 €",
    oldPrice: "199 €",
    vipPrice: "149 €",
    vipOldPrice: "249 €",
    seatsLeft: 11,
    closing: "Kevään ryhmän paikat täyttyvät",
    popular: false,
    recommend:
      "Sinua kiehtoo luonto, elämä ja ympäristö. Biologian valintakoe (C) painottaa aineiston soveltamista — harjoittelu tekee siitä vahvuutesi.",
    perks: [
      "Biologian ja ympäristötieteiden harjoitustehtävät",
      "Live-klinikat keväällä ja tallenteet",
      "Teoria ja painetut kirjat tulossa keväällä",
    ],
  },
];

export const getCourse = (code) => COURSES.find((c) => c.code === code);
